# Generated by Django 4.2.4 on 2023-08-27 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("total_weight", models.DecimalField(decimal_places=2, max_digits=4)),
                ("package", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=150)),
                ("pseudo_name", models.CharField(max_length=50)),
                ("price_per_ton_uah", models.SmallIntegerField(blank=True, null=True)),
                ("price_per_ton_eur", models.SmallIntegerField(blank=True, null=True)),
                ("product_photos", models.URLField(blank=True, null=True)),
                (
                    "goods",
                    models.OneToOneField(
                        blank=True,
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goods",
                    ),
                ),
                (
                    "uah_eur_rate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.currencyrates",
                    ),
                ),
            ],
        ),
    ]
