# Generated by Django 4.2.4 on 2023-08-28 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factory",
            name="goods",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.goods",
            ),
        ),
        migrations.AlterField(
            model_name="factory",
            name="uah_eur_rate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.currencyrates"
            ),
        ),
    ]
