# Generated by Django 4.2.4 on 2023-09-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0002_alter_factory_goods_alter_factory_uah_eur_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="factory",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
