# Generated by Django 4.2.4 on 2023-09-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0003_factory_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factory",
            name="status",
            field=models.BooleanField(db_column="Active", default=True),
        ),
    ]
