# Generated by Django 4.2.4 on 2023-08-27 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inquiry", "0001_initial"),
        ("goods", "0001_initial"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistanceCalculator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.FloatField(blank=True, null=True)),
                (
                    "checkpoints",
                    models.ManyToManyField(blank=True, to="main.countries"),
                ),
                (
                    "end_point",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inquiry.inquiry",
                    ),
                ),
                (
                    "start_point",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="goods.factory"
                    ),
                ),
            ],
            options={
                "unique_together": {("start_point", "end_point")},
            },
        ),
    ]
