# Generated by Django 4.2.4 on 2023-08-28 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiry", "0001_initial"),
        ("logistics", "0002_alter_distancecalculator_start_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distancecalculator",
            name="end_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inquiry.inquiry"
            ),
        ),
    ]
