# Generated by Django 4.2.4 on 2023-09-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inquiry", "0003_alter_inquiry_options_alter_customer_email_and_more"),
        ("goods", "0005_rename_status_factory_active"),
        ("logistics", "0003_alter_distancecalculator_end_point"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="distancecalculator",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="distancecalculator",
            name="zip_code",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="distancecalculator",
            unique_together={("start_point", "end_point", "zip_code")},
        ),
    ]
