# Generated by Django 4.2.4 on 2023-08-27 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("logistics", "0001_initial"),
        ("goods", "0001_initial"),
        ("inquiry", "0001_initial"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrimaryOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_fca", models.FloatField()),
                ("tonnage", models.FloatField(blank=True, null=True)),
                ("delivery_price", models.FloatField()),
                ("price_dap", models.FloatField()),
                (
                    "distance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_offer_distance",
                        to="logistics.distancecalculator",
                    ),
                ),
                (
                    "factories",
                    models.ManyToManyField(
                        related_name="factories", to="goods.factory"
                    ),
                ),
                (
                    "inquiry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiry",
                        to="inquiry.inquiry",
                    ),
                ),
                (
                    "marge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_offer_marge",
                        to="main.options",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UpdatedOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price", models.FloatField()),
                ("new_price", models.FloatField()),
                ("change_date", models.DateTimeField()),
                (
                    "delta_for_offer_update",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_offers",
                        to="main.options",
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_offers",
                        to="goods.goods",
                    ),
                ),
                (
                    "primary_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updated_offers",
                        to="offer.primaryoffer",
                    ),
                ),
            ],
        ),
    ]
