# Generated by Django 4.2.4 on 2023-08-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0003_alter_distancecalculator_end_point"),
        ("offer", "0002_alter_primaryoffer_delivery_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="primaryoffer",
            name="price_fca",
        ),
        migrations.AddField(
            model_name="primaryoffer",
            name="price_per_ton_eur",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="primaryoffer",
            name="distance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_offer_distance",
                to="logistics.distancecalculator",
            ),
        ),
    ]
