# Generated by Django 4.2.4 on 2023-08-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0003_alter_distancecalculator_end_point"),
        ("main", "0001_initial"),
        ("offer", "0004_remove_primaryoffer_price_per_ton_eur_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="primaryoffer",
            name="factories",
        ),
        migrations.AddField(
            model_name="primaryoffer",
            name="price_fca",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="primaryoffer",
            name="distance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_offer_distance",
                to="logistics.distancecalculator",
            ),
        ),
        migrations.AlterField(
            model_name="primaryoffer",
            name="marge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_offer_marge",
                to="main.options",
            ),
        ),
    ]
