# Generated by Django 4.2.4 on 2023-08-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0002_alter_factory_goods_alter_factory_uah_eur_rate"),
        ("offer", "0007_primaryoffer_factory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="primaryoffer",
            name="factory",
        ),
        migrations.AddField(
            model_name="primaryoffer",
            name="factories",
            field=models.ManyToManyField(
                related_name="primary_offers", to="goods.factory"
            ),
        ),
        migrations.AddField(
            model_name="primaryoffer",
            name="price_fca",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
