# Generated by Django 4.2.4 on 2023-08-28 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0008_remove_primaryoffer_factory_primaryoffer_factories_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="primaryoffer",
            name="factories",
        ),
    ]
