# Generated by Django 4.2.4 on 2023-08-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        ("inquiry", "0001_initial"),
        ("goods", "0002_alter_factory_goods_alter_factory_uah_eur_rate"),
        ("logistics", "0003_alter_distancecalculator_end_point"),
        ("offer", "0009_remove_primaryoffer_factories"),
    ]

    operations = [
        migrations.AddField(
            model_name="primaryoffer",
            name="factory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.factory",
            ),
        ),
        migrations.AddField(
            model_name="primaryoffer",
            name="photos",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="primaryoffer",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="goods.goods",
            ),
        ),
        migrations.AlterField(
            model_name="primaryoffer",
            name="distance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer_distances",
                to="logistics.distancecalculator",
            ),
        ),
        migrations.AlterField(
            model_name="primaryoffer",
            name="inquiry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="inquiry.inquiry",
            ),
        ),
        migrations.AlterField(
            model_name="primaryoffer",
            name="marge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer_marges",
                to="main.options",
            ),
        ),
    ]
