# Generated by Django 4.2.4 on 2023-08-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0011_alter_primaryoffer_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primaryoffer",
            name="distance",
            field=models.FloatField(),
        ),
    ]
