# Generated by Django 4.2.4 on 2023-09-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0004_alter_distancecalculator_unique_together_and_more"),
        ("offer", "0013_alter_primaryoffer_distance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primaryoffer",
            name="distance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offer_distances",
                to="logistics.distancecalculator",
            ),
        ),
    ]
